export const URL_API = {
    originUrl: 'http://localhost:8080',
    baseUrl: 'http://localhost:8080/api/v1',
    loginUrl: 'http://localhost:8080/api/v1/auth/login',
    registerUrl: 'http://localhost:8080/api/v1/auth/register',
    refreshTokenUrl: 'http://localhost:8080/api/v1/auth/refresh',
    introspect: 'http://localhost:8080/api/v1/auth/introspect',
    facebookLogin: 'http://localhost:8080/api/oauth2/authorization/facebook',
    googleLogin:   'http://localhost:8080/api/oauth2/authorization/google',
    productsUrl: 'http://localhost:8080/api/v1/products',
    catogoryUrl: 'http://localhost:8080/api/v1/category',
    checkProductNameExited: 'http://localhost:8080/api/v1/products/check-name',
    myInfo: 'http://localhost:8080/api/v1/users/myInfo',
    users: 'http://localhost:8080/api/v1/users',
    changePassword: 'http://localhost:8080/api/v1/users/myInfo/change-password',
    getOrders: 'http://localhost:8080/api/v1/orders',
    getOrderDetails: 'http://localhost:8080/api/v1/order-items',
    getOrdersAdmin: 'http://localhost:8080/api/v1/orders/filter/admin',
    getAllCouponsUser: 'http://localhost:8080/api/v1/coupons/user',
    getAllCouponsAdmin: 'http://localhost:8080/api/v1/coupons/admin',
    checkRoleAdmin: 'http://localhost:8080/api/v1/auth/checkRoleAdmin',
    promotionUrl:  'http://localhost:8080/api/v1/promotions',
} as const;
