export const URL_API = {
	originUrl: 'http://localhost:8080',
	baseUrl: 'http://localhost:8080/api/v1',
	loginUrl: 'http://localhost:8080/api/v1/auth/login',
	registerUrl: 'http://localhost:8080/api/v1/auth/register',
	refreshTokenUrl: 'http://localhost:8080/api/v1/auth/refresh',
	introspect: 'http://localhost:8080/api/v1/auth/introspect',
	facebookLogin: 'http://localhost:8080/api/oauth2/authorization/facebook',
	googleLogin: 'http://localhost:8080/api/oauth2/authorization/google',
	productsUrl: 'http://localhost:8080/api/v1/products',
	catogoryUrl: 'http://localhost:8080/api/v1/category',
	checkProductNameExited: 'http://localhost:8080/api/v1/products/check-name',
	myInfo: 'http://localhost:8080/api/v1/users/myInfo',
	users: 'http://localhost:8080/api/v1/users',
	changePassword: 'http://localhost:8080/api/v1/users/myInfo/change-password',
	getOrders: 'http://localhost:8080/api/v1/orders',
	getOrderDetails: 'http://localhost:8080/api/v1/order-items',
	getOrdersAdmin: 'http://localhost:8080/api/v1/orders/filter/admin',
	getAllCouponsUser: 'http://localhost:8080/api/v1/coupons/user',
	getAllCouponsFilterAdmin: 'http://localhost:8080/api/v1/coupons/admin/filter',
	checkRoleAdmin: 'http://localhost:8080/api/v1/auth/checkRoleAdmin',
	promotionFilter: 'http://localhost:8080/api/v1/promotions/filter',
	avtivePromotionUrl:
		'http://localhost:8080/api/v1/promotions/active-promotions',
	promotionUrl: 'http://localhost:8080/api/v1/promotions',
	userFilterAdmin: 'http://localhost:8080/api/v1/users/admin/filter',
	categoryFilter: 'http://localhost:8080/api/v1/category/admin/filter',
	getAllCouponsAdmin: 'http://localhost:8080/api/v1/coupons/admin',
	purchaseOrders: 'http://localhost:8080/api/v1/purchase-orders',
	suppliers: 'http://localhost:8080/api/v1/supplier',
	inventory: 'http://localhost:8080/api/v1/inventory',
  createCategory: 'http://localhost:8080/api/v1/category/admin/create',
  coupon: 'http://localhost:8080/api/v1/coupons',
} as const;
