server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data
    username: myuser
    password: myuser
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      #      ddl-auto:     create
      ddl-auto: update

    show-sql: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1336955447356626
            client-secret: f63f179e6acd273f9c1583860b555769
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            scope:
              - email
              - public_profile
            client-name: Facebook
            authorization-grant-type: authorization_code
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Hiển thị log chi tiết cho Spring Security

jwt:
  key: AaGpWmjmTnXtXbAR+Dkx/GTU5oV26NvIP/BWkm1btLZmm28hoUwBljJo6Cgy/X/4
  valid-duration: 86400 # in second   1 day
  refreshable-duration: 604800 # in second  1 week
schedules:
  reset-invalidated-token: "0 0 0 * * ?" # Chạy vào 00:00  mỗi ngày

app:
  frontend:
    url: http://localhost:4200