server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/data
     username: myuser
     password: myuser
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto:     create
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1336955447356626
            client-secret: f63f179e6acd273f9c1583860b555769
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            scope:
              - email
              - public_profile
            client-name: Facebook
            authorization-grant-type: authorization_code
          google:
            client-id: 22261971260-9gv8aaldds89h0k3o5fldss6hlofem55.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: openid, email, profile

        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Hiển thị log chi tiết cho Spring Security

jwt:
  key: AaGpWmjmTnXtXbAR+Dkx/GTU5oV26NvIP/BWkm1btLZmm28hoUwBljJo6Cgy/X/4
  valid-duration: 18000 # in second 5 hour
  refreshable-duration: 604800 # in second 1 week
schedules:
  reset-invalidated-token: "0 0 0 * * ?" # Chạy vào 00:00  mỗi ngày

app:
  frontend:
    url: http://localhost:4200