server:
  port: 8080
  servlet:
    context-path: /home

spring:
  datasource:
    url: "jdbc:mysql://localhost/db"
    username: 'root'
    password: 'root'
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


