server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_CONNECTION_USERNAME}
    password: ${DBMS_CONNECTION_PASSWORD}
    driver-class-name: org.postgresql.Driver
  #    hikari:
  #      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379

jwt:
  key: ${JWT_KEY}
  valid-duration: 86400 # in second   1 day
  refreshable-duration: 604800 # in second  1 week
schedules:
  reset-invalidated-token: "0 0 0 * * ?" # Chạy vào 00:00  mỗi ngày
